"""add field to users

Revision ID: 293167e2b3d2
Revises: 371c0c95d78d
Create Date: 2022-10-20 11:41:13.319594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293167e2b3d2'
down_revision = '371c0c95d78d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_field')
    # ### end Alembic commands ###
