"""drop column

Revision ID: b916e4248cde
Revises: 293167e2b3d2
Create Date: 2022-10-20 23:58:45.256819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b916e4248cde'
down_revision = '293167e2b3d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job')
    op.drop_column('users', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('job', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
