"""add job to users

Revision ID: c2b9a457c42f
Revises: a36322a9fe7b
Create Date: 2022-10-18 17:28:20.629038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b9a457c42f'
down_revision = 'a36322a9fe7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job')
    # ### end Alembic commands ###
